<project name="PicardFilterWheel">
   <import file="../../../buildscripts/deviceadapter.xml"/>

	<property name="picard.filterwheel.sdk" location="${mm.thirdpartypublic}/Picard/USB Filter V1.4/PiUsbSDK"/>

	<target name="install-Win32">
		<copy todir="${mm.dll.installdir}" file="${picard.filterwheel.sdk}/bin/Win32/PiUsb.dll"/>
	</target>

	<target name="install-x64">
		<copy todir="${mm.dll.installdir}" file="${picard.filterwheel.sdk}/bin/x64/PiUsb.dll"/>
	</target>
</project>
